/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DefaultLayout: typeof import('./src/app/layouts/DefaultLayout.vue')['default']
    ProductCard: typeof import('./src/features/products/components/ProductCard.vue')['default']
    ProductCatalogPage: typeof import('./src/features/products/pages/ProductCatalogPage.vue')['default']
    ProductGrid: typeof import('./src/features/products/components/ProductGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/widgets/footer/TheFooter.vue')['default']
    TheHeader: typeof import('./src/widgets/header/TheHeader.vue')['default']
  }
}

// For TSX support
declare global {
  const DefaultLayout: typeof import('./src/app/layouts/DefaultLayout.vue')['default']
  const ProductCard: typeof import('./src/features/products/components/ProductCard.vue')['default']
  const ProductCatalogPage: typeof import('./src/features/products/pages/ProductCatalogPage.vue')['default']
  const ProductGrid: typeof import('./src/features/products/components/ProductGrid.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TheFooter: typeof import('./src/widgets/footer/TheFooter.vue')['default']
  const TheHeader: typeof import('./src/widgets/header/TheHeader.vue')['default']
}